# -*- coding: utf-8 -*-
"""Level4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B-8uR5tCi8vP8Q52jnj6LUnM2q90FfHM
"""

import pandas as pd
data = pd.read_csv('/content/Heart_Disease.csv')

df = pd.DataFrame(data, columns = ["HeartDiseaseorAttack", "BMI", "Age", "Income", "Diabetes_binary", "HighBP", "HighChol", "CholCheck", "BMI", "Smoker", "Stroke", "PhysActivity", "Fruits", "Veggies", "HvyAlcoholConsump", "Sex", "Age", "Education", "Income"])
x = pd.DataFrame(data, columns = ["BMI", "Age", "Income", "Diabetes_binary", "HighBP", "HighChol", "CholCheck", "BMI", "Smoker", "Stroke", "PhysActivity", "Fruits", "Veggies", "HvyAlcoholConsump", "Sex", "Age", "Education", "Income"])

y = data[["HeartDiseaseorAttack"]]

from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(12, input_dim=8, activation="relu"))
model.add(Dense(12, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

model = Sequential([ ])
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
hist=model.fit(x,y, epochs=150, batch_size=10)

_, accuracy = model.evaluate(x, y)
print("Model accuracy: %.2f"% (accuracy*100))

predictions = model.predict(x)
print([round(x[0]) for x in predictions])

predictions = model.predict(x)
print([round(x[1]) for x in predictions])